# -*- coding: utf-8 -*-

from . import models
from . import custom_data_type
from . import custom_data
from . import custom_fired
from . import custom_holiday
from . import custom_settlement
from . import custom_afp
from . import custom_benefits_rrhh
from . import custom_isapre
from . import custom_indicators
from . import hr_contract
from . import hr_salary_rule
from . import hr_payslip
from . import custom_indicators_data
from . import custom_mutuality_by_company
from . import custom_unique_tax
from . import wizard_hr_payslip
from . import hr_department
from . import hr_employee
from . import custom_employee_type
from . import hr_payslip_worked_days
from . import resource_calendar
from . import res_company
from . import custom_payslip_payment_term
from . import custom_loan
from . import custom_fee
from . import confirm_loan
from . import custom_personal_movements
from . import custom_permanent_discounts
from . import hr_payslip_input
from . import custom_other_savings
from . import res_currency
from . import account_move
from . import custom_sale_employee
from . import custom_vacation
from . import hr_leave
from . import custom_payslip_overdraft
from . import custom_confirm_undo_payslip
from . import hr_leave_allocation
from . import custom_contract_period
from . import custom_contract_document
from . import custom_contract_document_type
from . import custom_leave_allocation_period